
version: "3"
services:
  app:
    image: denoland/deno
    volumes:
    - "./src:/app"
    command: deno run --allow-net --allow-env --allow-write --allow-read /app/hipica/server.ts
    ports:
      - "8000:8000"
    depends_on:
      - pgsql_db

  pgsql_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: deno_hipica
    volumes:
    - ./src/hipica/resources/create_database.sql:/docker-entrypoint-initdb.d/init.sql

  
  adminer:
    image: wodby/adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: pgsql_db
      ADMINER_DEFAULT_DB_NAME: deno_hipica
      ADMINER_DESIGN: pilot
    ports:
      - 8080:9000